name: Build and Deploy Retell SDK

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js 18

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm audit fix --audit-level=moderate  # Automatically fix vulnerabilities

      # Build the bundles
      - name: Build SDK Bundles
        run: |
          npm run build
          
      # Add, commit, and push changes to the dist folder
      - name: Commit and Push Bundles
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/
          git commit -m "Build new Retell SDK bundles"
          git push

      # Run audit report
      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate


      # Run audit report
      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate
