name: Build and Deploy Retell SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install --save-dev webpack webpack-cli babel-loader @babel/core @babel/preset-env

      - name: Set up build-project directory
        run: |
          mkdir -p build-project/src
          echo "import { RetellWebClient } from 'retell-client-js-sdk'; window.retellWebClient = new RetellWebClient();" > build-project/src/index.js

      - name: Set up Webpack configuration for both full and minified versions
        run: |
          echo "const path = require('path');
          module.exports = [
            {
              entry: './build-project/src/index.js',
              output: {
                path: path.resolve(__dirname, 'dist'),
                filename: 'retell-sdk-${{ env.VERSION }}-bundle.js',
              },
              module: {
                rules: [
                  {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                      loader: 'babel-loader',
                      options: {
                        presets: ['@babel/preset-env'],
                      },
                    },
                  },
                ],
              },
              mode: 'production',
            },
            {
              entry: './build-project/src/index.js',
              output: {
                path: path.resolve(__dirname, 'dist'),
                filename: 'retell-sdk-${{ env.VERSION }}-bundle.min.js',
              },
              module: {
                rules: [
                  {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                      loader: 'babel-loader',
                      options: {
                        presets: ['@babel/preset-env'],
                      },
                    },
                  },
                ],
              },
              mode: 'production',
              optimization: {
                minimize: true,  // This enables minification
              },
            },
          ];" > webpack.config.js

      - name: Build with Webpack
        run: |
          npx webpack --config webpack.config.js

      - name: Commit and push generated bundles to GitHub
        run: |
          # Configure git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the generated files to git
          git add dist/retell-sdk-${{ env.VERSION }}-bundle.js
          git add dist/retell-sdk-${{ env.VERSION }}-bundle.min.js
          
          # Commit the changes
          git commit -m "Add full and minified SDK bundles for version ${{ env.VERSION }}"

          # Push the changes back to the repository
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
