name: Build and Bundle Retell SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g parcel@latest
          npm install
          npm install retell-client-js-sdk --save

      - name: Get Retell SDK Version
        id: get-version
        run: echo "VERSION=$(npm view retell-client-js-sdk version)" >> $GITHUB_ENV

      - name: Build the SDK bundle
        run: |
          mkdir -p build-project/src
          echo "import { RetellWebClient } from 'retell-client-js-sdk'; window.retellWebClient = new RetellWebClient();" > build-project/src/index.js
          cd build-project
          NODE_ENV=production npx parcel build src/index.js --dist-dir ../dist --no-source-maps --no-cache
          cd ..

      - name: Rename bundles with version
        run: |
          if [ -f dist/index.js ]; then
            mv dist/index.js dist/retell-sdk-${{ env.VERSION }}-bundle.js
          else
            echo "Error: dist/index.js not found"
            exit 1
          fi

          if [ -f dist/index.js ]; then
            cp dist/retell-sdk-${{ env.VERSION }}-bundle.js dist/retell-sdk-${{ env.VERSION }}-bundle.min.js
          else
            echo "Error: Minified file not generated, creating from unminified version"
            npx terser dist/retell-sdk-${{ env.VERSION }}-bundle.js -o dist/retell-sdk-${{ env.VERSION }}-bundle.min.js
          fi

      - name: Add and Commit Bundles
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/retell-sdk-${{ env.VERSION }}-bundle.js dist/retell-sdk-${{ env.VERSION }}-bundle.min.js
          git commit -m "Add bundled files for Retell SDK v${{ env.VERSION }}"
          git push
