name: Bundle Retell SDK

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use the latest stable Node.js version

      - name: Install dependencies
        run: |
          # Install npm dependencies, including retell-client-js-sdk
          npm install

      - name: Install Retell SDK
        run: |
          npm install retell-client-js-sdk  # Install the retell-client-js-sdk package

      - name: Create index.js for bundling
        run: |
          mkdir -p src
          echo "import { RetellWebClient } from 'retell-client-js-sdk';" > src/index.js
          echo "window.retellWebClient = new RetellWebClient();" >> src/index.js

      - name: Get Retell SDK Version
        id: get-version
        run: |
          # Extract the installed version of retell-client-js-sdk directly from package.json using jq
          SDK_VERSION=$(jq -r '.dependencies["retell-client-js-sdk"]' package.json | sed 's/^@//;s/\//-/;s/^\^//')  # Remove the ^ character
          echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV

      - name: Bundle Retell SDK (Full Version)
        run: |
          # Use the version in the filename for the full version
          npx esbuild src/index.js --bundle --outfile=dist/retell-bundle-${{ env.SDK_VERSION }}.js

      - name: Bundle Retell SDK (Minified Version)
        run: |
          # Use the version in the filename for the minified version
          npx esbuild src/index.js --bundle --minify --outfile=dist/retell-bundle-${{ env.SDK_VERSION }}.min.js

      - name: Commit bundled files to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Force add the bundled files to the commit even if they're ignored by .gitignore
          git add -f dist/retell-bundle-${{ env.SDK_VERSION }}.js
          git add -f dist/retell-bundle-${{ env.SDK_VERSION }}.min.js
          
          # Commit the changes with a message reflecting the version of the SDK
          git commit -m "Update retell-bundles to version ${{ env.SDK_VERSION }}"

          # Push the changes back to the repository
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag for Version
        run: |
          # Create a Git tag for the current SDK version
          git tag "v${{ env.SDK_VERSION }}"

          # Push the Git tag to the repository
          git push origin "v${{ env.SDK_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
