name: Build and Deploy JS SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (version 18.x as an example, you can change as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Ensure webpack and webpack-cli are installed
      - name: Ensure webpack and webpack-cli are installed
        run: |
          npm install --save-dev webpack webpack-cli

      # Install retell-client-js-sdk (if not in package.json already)
      - name: Install retell-client-js-sdk
        run: |
          npm install retell-client-js-sdk

      # Verify installation of dependencies
      - name: Verify installation
        run: |
          npm ls webpack
          npm ls webpack-cli
          npm ls retell-client-js-sdk

      # Build the project with Webpack
      - name: Run Webpack build
        run: |
          npx webpack --config webpack.config.js

      # Commit the created bundles to repository
      - name: Commit bundles to repository
        run: |
          git add ./dist/
          git commit -m "Add built bundles"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
