name: Bundle Retell SDK for Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Install retell-client-js-sdk
      run: |
        npm install retell-client-js-sdk

    - name: Bundle Retell SDK with full and minified versions
      run: |
        # Install parcel if necessary
        npm install -g parcel

        # Create a directory for the bundle if it doesn't exist
        mkdir -p dist

        # Create a JavaScript file to initialize the Retell SDK
        echo "import { RetellWebClient } from 'retell-client-js-sdk';" > src/index.js
        echo "window.retellWebClient = new RetellWebClient();" >> src/index.js

        # Build the bundle using parcel
        npx parcel build src/index.js --out-dir dist --no-source-maps --public-url ./ --minify

    - name: Extract SDK version
      run: |
        # Extract the installed version of retell-client-js-sdk
        SDK_VERSION=$(npm list retell-client-js-sdk | grep retell-client-js-sdk | awk '{print $2}' | sed 's/@/-/g')
        echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV

    - name: Rename bundled files with version number
      run: |
        # Rename the output files to include the version number
        mv dist/index.js dist/retell-bundle-${{ env.SDK_VERSION }}.js
        mv dist/index.min.js dist/retell-bundle-${{ env.SDK_VERSION }}.min.js

    - name: Commit bundled files to repo
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Force add the bundled files to the commit even if they're ignored by .gitignore
        git add -f dist/retell-bundle-${{ env.SDK_VERSION }}.js
        git add -f dist/retell-bundle-${{ env.SDK_VERSION }}.min.js
        
        # Commit the changes with a message reflecting the version of the SDK
        git commit -m "Update retell-bundles to version ${{ env.SDK_VERSION }}"

        # Push the changes back to the repository
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Git tag for the bundled version
      run: |
        # Create a Git tag for the current version
        git tag "v${{ env.SDK_VERSION }}"

        # Push the tag to the repository
        git push origin "v${{ env.SDK_VERSION }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
