name: Sync with Upstream

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3

      - name: Set Git user configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/RetellAI/retell-client-js-sdk.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Attempt to merge changes
        id: merge
        run: |
          git merge upstream/main --allow-unrelated-histories || echo "Merge conflicts detected" && exit 1

      - name: Resolve merge conflicts (force ours strategy)
        if: failure()
        run: |
          # Forcefully prefer fork's changes for all files
          git merge --strategy-option ours upstream/main || true
          git ls-files -u | awk '{print $4}' | xargs git add
          git commit -m "Resolve merge conflicts preferring fork changes"

      - name: Push changes
        run: git push
