name: Sync with Upstream

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3

      - name: Add upstream repository
        run: git remote add upstream https://github.com/RetellAI/retell-client-js-sdk.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge changes into fork
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: git push
